### ISSUE TITLE
Is this example still valid?

### ISSUE THREAD

**Issue by PsyKoMari** [datvt9312/flutter_i18n_plugin#1]
I cloned your repository, opened in android studio with the latest version of the plugin installed and got errors when changing languages.

When I tap the button the Text changes to Fr but also got this error on the screen of the simulator and in flutter console

```
flutter: ════════
flutter: Warning: This application's locale, fr_, is not supported by all of its
flutter: localization delegates.
flutter: > A MaterialLocalizations delegate that supports the fr_ locale was not found.
flutter: See https://flutter.io/tutorials/internationalization/ for more
flutter: information about configuring an app's locale, supportedLocales,
flutter: and localizationsDelegates parameters.
flutter: ════════
flutter:
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building AppBar(dirty, dependencies:
flutter: [_LocalizationsScope-[GlobalKey#cc3a7], _InheritedTheme, _ModalScopeStatus], state:
flutter: _AppBarState#b2482):
flutter: No MaterialLocalizations found.
flutter: AppBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
flutter: Localizations are used to generate many different messages, labels,and abbreviations which are used
flutter: by the material library.
flutter: To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
flutter: include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
flutter: The specific widget that could not find a MaterialLocalizations ancestor was:
flutter:   AppBar
flutter: The ancestors of this widget were:
flutter:   FlexibleSpaceBarSettings
flutter:   ConstrainedBox(BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=100.0))
flutter:   MediaQuery(MediaQueryData(size: Size(375.0, 812.0), devicePixelRatio: 3.0, textScaleFactor: 1.0,
flutter:   platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 44.0, 0.0, 0.0), viewInsets:
flutter:   EdgeInsets.zero, alwaysUse24HourFormat: true, accessibleNavigation: falsedisableAnimations:
flutter:   falseinvertColors: falseboldText: false))
flutter:   LayoutId-[<_ScaffoldSlot.appBar>](id: _ScaffoldSlot.appBar)
flutter:   CustomMultiChildLayout
flutter:   AnimatedBuilder(animation: AnimationController#56ce1(⏭ 1.000; paused))
flutter:   DefaultTextStyle(debugLabel: (englishLike body1 2014).merge(blackCupertino body1), inherit: false,
flutter:   color: Color(0xdd000000), family: .SF UI Text, size: 14.0, weight: 400, baseline: alphabetic,
flutter:   decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
flutter:   AnimatedDefaultTextStyle(duration: 200ms, debugLabel: (englishLike body1
flutter:   2014).merge(blackCupertino body1), inherit: false, color: Color(0xdd000000), family: .SF UI Text,
flutter:   size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping
flutter:   at box width, overflow: clip)
flutter:   _InkFeatures-[GlobalKey#d9e0c ink renderer]
flutter:   NotificationListener<LayoutChangedNotification>
flutter:   PhysicalModel(shape: rectangle, borderRadius: BorderRadius.zero, elevation: 0.0, color:
flutter:   Color(0xfffafafa), shadowColor: Color(0xff000000))
flutter:   AnimatedPhysicalModel(duration: 200ms, shape: rectangle, borderRadius: BorderRadius.zero,
flutter:   elevation: 0.0, color: Color(0xfffafafa), animateColor: false, shadowColor: Color(0xff000000),
flutter:   animateShadowColor: true)
flutter:   Material(type: canvas, color: Color(0xfffafafa))
flutter:   PrimaryScrollController(ScrollController#0d3a2(no clients))
flutter:   _ScaffoldScope
flutter:   Scaffold
flutter:   AppBody
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter:   hintOverrides: null)
flutter:   Builder
flutter:   RepaintBoundary-[GlobalKey#7bc59]
flutter:   IgnorePointer(ignoring: false)
flutter:   Stack(alignment: AlignmentDirectional.topStart, fit: passthrough, overflow: clip)
flutter:   _CupertinoBackGestureDetector<dynamic>
flutter:   DecoratedBox(bg: _CupertinoEdgeShadowDecoration(edgeGradient:
flutter:   LinearGradient(AlignmentDirectional(0.9, 0.0), AlignmentDirectional.centerEnd, [Color(0x00000000),
flutter:   Color(0x04000000), Color(0x12000000), Color(0x38000000)], [0.0, 0.3, 0.6, 1.0], TileMode.clamp)))
flutter:   DecoratedBoxTransition(animation: AnimationController#be2b0(⏭ 1.000; paused; for
flutter:   MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.35, 0.91, 0.33,
flutter:   0.97)➩DecorationTween(_CupertinoEdgeShadowDecoration(edgeGradient: null) →
flutter:   _CupertinoEdgeShadowDecoration(edgeGradient: LinearGradient(AlignmentDirectional(0.9, 0.0),
flutter:   AlignmentDirectional.centerEnd, [Color(0x00000000), Color(0x04000000), Color(0x12000000),
flutter:   Color(0x38000000)], [0.0, 0.3, 0.6, 1.0],
flutter:   TileMode.clamp)))➩_CupertinoEdgeShadowDecoration(edgeGradient:
flutter:   LinearGradient(AlignmentDirectional(0.9, 0.0), AlignmentDirectional.centerEnd, [Color(0x00000000),
flutter:   Color(0x04000000), Color(0x12000000), Color(0x38000000)], [0.0, 0.3, 0.6, 1.0], TileMode.clamp)))
flutter:   FractionalTranslation
flutter:   SlideTransition(animation: AnimationController#be2b0(⏭ 1.000; paused; for
flutter:   MaterialPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.35, 0.91, 0.33, 0.97)ₒₙ/Cubic(0.67, 0.03,
flutter:   0.65, 0.09)➩Tween<Offset>(Offset(1.0, 0.0) → Offset(0.0, 0.0))➩Offset(0.0, 0.0))
flutter:   FractionalTranslation
flutter:   SlideTransition(animation: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation➩Cubic(0.35,
flutter:   0.91, 0.33, 0.97)ₒₙ/Cubic(0.67, 0.03, 0.65, 0.09)➩Tween<Offset>(Offset(0.0, 0.0) → Offset(-0.3,
flutter:   0.0))➩Offset(0.0, 0.0))
flutter:   CupertinoPageTransition
flutter:   AnimatedBuilder(animation: Listenable.merge([AnimationController#be2b0(⏭ 1.000; paused; for
flutter:   MaterialPageRoute<dynamic>(/))➩ProxyAnimation,
flutter:   kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation]))
flutter:   RepaintBoundary
flutter:   _FocusScopeMarker
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter:   hintOverrides: null)
flutter:   FocusScope
flutter:   PageStorage
flutter:   Offstage(offstage: false)
flutter:   _ModalScopeStatus(active)
flutter:   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#8e5d2]
flutter:   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#33457]
flutter:   Stack(alignment: AlignmentDirectional.topStart, fit: expand, overflow: clip)
flutter:   _Theatre
flutter:   Overlay-[LabeledGlobalKey<OverlayState>#a1e19]
flutter:   _FocusScopeMarker
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter:   hintOverrides: null)
flutter:   FocusScope
flutter:   AbsorbPointer(absorbing: false)
flutter:   Listener(listeners: [down, up, cancel], behavior: deferToChild)
flutter:   Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#b56ac]
flutter:   CupertinoTheme
flutter:   IconTheme(IconThemeData#2abdc(color: Color(0xdd000000)))
flutter:   _InheritedTheme
flutter:   Theme(ThemeData#3470b(buttonTheme: ButtonThemeData#f4e79(buttonColor: Color(0xffe0e0e0),
flutter:   colorScheme: ColorScheme#ac5f1(primary: MaterialColor(primary value: Color(0xff2196f3)),
flutter:   primaryVariant: Color(0xff1976d2), secondary: Color(0xff2196f3), secondaryVariant:
flutter:   Color(0xff1976d2), background: Color(0xff90caf9), error: Color(0xffd32f2f), onSecondary:
flutter:   Color(0xffffffff), onBackground: Color(0xffffffff)), materialTapTargetSize:
flutter:   MaterialTapTargetSize.padded), textTheme: TextTheme#4e22a, primaryTextTheme:
flutter:   TextTheme#e860f(display4: TextStyle(debugLabel: whiteCupertino display4, inherit: true, color:
flutter:   Color(0xb3ffffff), family: .SF UI Display, decoration: TextDecoration.none), display3:
flutter:   TextStyle(debugLabel: whiteCupertino display3, inherit: true, color: Color(0xb3ffffff), family:
flutter:   .SF UI Display, decoration: TextDecoration.none), display2: TextStyle(debugLabel: whiteCupertino
flutter:   display2, inherit: true, color: Color(0xb3ffffff), family: .SF UI Display, decoration:
flutter:   TextDecoration.none), display1: TextStyle(debugLabel: whiteCupertino display1, inherit: true,
flutter:   color: Color(0xb3ffffff), family: .SF UI Display, decoration: TextDecoration.none), headline:
flutter:   TextStyle(debugLabel: whiteCupertino headline, inherit: true, color: Color(0xffffffff), family:
flutter:   .SF UI Display, decoration: TextDecoration.none), title: TextStyle(debugLabel: whiteCupertino
flutter:   title, inherit: true, color: Color(0xffffffff), family: .SF UI Display, decoration:
flutter:   TextDecoration.none), subhead: TextStyle(debugLabel: whiteCupertino subhead, inherit: true, color:
flutter:   Color(0xffffffff), family: .SF UI Text, decoration: TextDecoration.none), body2:
flutter:   TextStyle(debugLabel: whiteCupertino body2, inherit: true, color: Color(0xffffffff), family: .SF
flutter:   UI Text, decoration: TextDecoration.none), body1: TextStyle(debugLabel: whiteCupertino body1,
flutter:   inherit: true, color: Color(0xffffffff), family: .SF UI Text, decoration: TextDecoration.none),
flutter:   caption: TextStyle(debugLabel: whiteCupertino caption, inherit: true, color: Color(0xb3ffffff),
flutter:   family: .SF UI Text, decoration: TextDecoration.none), button: TextStyle(debugLabel:
flutter:   whiteCupertino button, inherit: true, color: Color(0xffffffff), family: .SF UI Text, decoration:
flutter:   TextDecoration.none), subtitle): TextStyle(debugLabel: whiteCupertino subtitle, inherit: true,
flutter:   color: Color(0xffffffff), family: .SF UI Text, decoration: TextDecoration.none), overline:
flutter:   TextStyle(debugLabel: whiteCupertino overline, inherit: true, color: Color(0xffffffff), family:
flutter:   .SF UI Text, decoration: TextDecoration.none)), accentTextTheme: TextTheme#e860f(display4:
flutter:   TextStyle(debugLabel: whiteCupertino display4, inherit: true, color: Color(0xb3ffffff), family:
flutter:   .SF UI Display, decoration: TextDecoration.none), display3: TextStyle(debugLabel: whiteCupertino
flutter:   display3, inherit: true, color: Color(0xb3ffffff), family: .SF UI Display, decoration:
flutter:   TextDecoration.none), display2: TextStyle(debugLabel: whiteCupertino display2, inherit: true,
flutter:   color: Color(0xb3ffffff), family: .SF UI Display, decoration: TextDecoration.none), display1:
flutter:   TextStyle(debugLabel: whiteCupertino display1, inherit: true, color: Color(0xb3ffffff), family:
flutter:   .SF UI Display, decoration: TextDecoration.none), headline: TextStyle(debugLabel: whiteCupertino
flutter:   headline, inherit: true, color: Color(0xffffffff), family: .SF UI Display, decoration:
flutter:   TextDecoration.none), title: TextStyle(debugLabel: whiteCupertino title, inherit: true, color:
flutter:   Color(0xffffffff), family: .SF UI Display, decoration: TextDecoration.none), subhead:
flutter:   TextStyle(debugLabel: whiteCupertino subhead, inherit: true, color: Color(0xffffffff), family: .SF
flutter:   UI Text, decoration: TextDecoration.none), body2: TextStyle(debugLabel: whiteCupertino body2,
flutter:   inherit: true, color: Color(0xffffffff), family: .SF UI Text, decoration: TextDecoration.none),
flutter:   body1: TextStyle(debugLabel: whiteCupertino body1, inherit: true, color: Color(0xffffffff),
flutter:   family: .SF UI Text, decoration: TextDecoration.none), caption: TextStyle(debugLabel:
flutter:   whiteCupertino caption, inherit: true, color: Color(0xb3ffffff), family: .SF UI Text, decoration:
flutter:   TextDecoration.none), button: TextStyle(debugLabel: whiteCupertino button, inherit: true, color:
flutter:   Color(0xffffffff), family: .SF UI Text, decoration: TextDecoration.none), subtitle):
flutter:   TextStyle(debugLabel: whiteCupertino subtitle, inherit: true, color: Color(0xffffffff), family:
flutter:   .SF UI Text, decoration: TextDecoration.none), overline: TextStyle(debugLabel: whiteCupertino
flutter:   overline, inherit: true, color: Color(0xffffffff), family: .SF UI Text, decoration:
flutter:   TextDecoration.none)), inputDecorationTheme: InputDecorationTheme#db7ff, iconTheme:
flutter:   IconThemeData#2abdc(color: Color(0xdd000000)), primaryIconTheme: IconThemeData#15fa8(color:
flutter:   Color(0xffffffff)), accentIconTheme: IconThemeData#15fa8(color: Color(0xffffffff)), sliderTheme:
flutter:   SliderThemeData#04b73, tabBarTheme: TabBarTheme#e3dcc, cardTheme: CardTheme#b4e63, chipTheme:
flutter:   ChipThemeData#d68ec, materialTapTargetSize: MaterialTapTargetSize.padded, pageTransitionsTheme:
flutter:   PageTransitionsTheme#cdcb4))
flutter:   AnimatedTheme(duration: 200ms)
flutter:   Builder
flutter:   DefaultTextStyle(debugLabel: fallback style; consider putting your text in a Material, inherit:
flutter:   true, color: Color(0xd0ff0000), family: monospace, size: 48.0, weight: 900, decoration: double
flutter:   Color(0xffffff00) TextDecoration.underline, softWrap: wrapping at box width, overflow: clip)
flutter:   CustomPaint
flutter:   Banner("DEBUG", textDirection: ltr, location: topEnd, Color(0xa0b71c1c), text inherit: true, text
flutter:   color: Color(0xffffffff), text size: 10.2, text weight: 900, text height: 1.0x)
flutter:   CheckedModeBanner("DEBUG")
flutter:   Title(color: MaterialColor(primary value: Color(0xff2196f3)))
flutter:   Directionality(textDirection: ltr)
flutter:   _LocalizationsScope-[GlobalKey#cc3a7]
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter:   textDirection: ltr, hintOverrides: null)
flutter:   Localizations(locale: fr_, delegates: [GeneratedLocalizationsDelegate[S],
flutter:   DefaultMaterialLocalizations.delegate(en_US), DefaultCupertinoLocalizations.delegate(en_US),
flutter:   DefaultWidgetsLocalizations.delegate(en_US)])
flutter:   MediaQuery(MediaQueryData(size: Size(375.0, 812.0), devicePixelRatio: 3.0, textScaleFactor: 1.0,
flutter:   platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 44.0, 0.0, 34.0), viewInsets:
flutter:   EdgeInsets.zero, alwaysUse24HourFormat: true, accessibleNavigation: falsedisableAnimations:
flutter:   falseinvertColors: falseboldText: false))
flutter:   WidgetsApp-[GlobalObjectKey _MaterialAppState#aff8d]
flutter:   ScrollConfiguration(behavior: _MaterialScrollBehavior)
flutter:   MaterialApp
flutter:   App
flutter:   [root]
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:124:7)
flutter: #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
flutter: #2      _AppBarState.build (package:flutter/src/material/app_bar.dart:389:12)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #10     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #16     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #22     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #23     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #31     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #47     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #51     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #59     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #73     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #75     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #77     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #79     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #80     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #84     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #90     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #106    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #110    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #116    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #126    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #128    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #130    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #131    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #132    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #136    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #140    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #141    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
flutter: #145    _invoke (dart:ui/hooks.dart:209:10)
flutter: #146    _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mohammed-jaouad** [comment]
Hello,
I had the same problem, you have to add localizations to your pubspec.yaml in your dependencies : 
```
  flutter_localizations:
    sdk: flutter
```
And in your main you have to add GlobalMaterialLocalizations and GlobalWidgetsLocalizations delegates, you should have something like : 
```
localizationsDelegates: [
          S.delegate,
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
```
It worked for me. 

Good luck.
